name: deploy to lambda
on:
  push:
    branches: [ main ]
jobs:
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16.x]
    steps:
      - name: checkout source code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build binary
        run: |
          cd src && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o main main.go && zip deployment.zip main

      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region:  ${{ secrets.AWS_REGION }}
          function_name: scaler
          zip_file: src/deployment.zip
          memory_size: 256
          timeout: 300
          handler: main
          runtime: go1.x